name: dbt Pipeline

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dbt
        run: |
          pip uninstall -y dbt-core dbt-snowflake
          pip install dbt-core==1.8.0 dbt-snowflake==1.8.0
      
      - name: Create profiles directory
        run: |
          mkdir -p ~/.dbt
          cp personal_finance_analytics/profiles_ci.yml ~/.dbt/profiles.yml
      
      - name: Run dbt pipeline
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        working-directory: ./personal_finance_analytics
        run: |
          echo "Warehouse: $SNOWFLAKE_WAREHOUSE"
          echo "Database: $SNOWFLAKE_DATABASE"
          dbt --version
          dbt debug
          dbt deps
          dbt run
          dbt test